export type MenuItem = {
  code: string;
  name: string;
  price: number;
  category: string;
};

export const DEFAULT_MENU: MenuItem[] = [
  { code: "101", name: "Idli (2 pcs)", price: 40, category: "Tiffin" },
  { code: "102", name: "Plain Dosa", price: 70, category: "Tiffin" },
  { code: "103", name: "Masala Dosa", price: 90, category: "Tiffin" },
  { code: "104", name: "Onion Dosa", price: 100, category: "Tiffin" },
  { code: "105", name: "Ghee Roast Dosa", price: 120, category: "Tiffin" },
  { code: "106", name: "Pongal", price: 80, category: "Tiffin" },
  { code: "107", name: "Poori (2 pcs)", price: 75, category: "Tiffin" },
  { code: "108", name: "Medhu Vada (2 pcs)", price: 50, category: "Tiffin" },
  { code: "109", name: "Rava Kesari", price: 45, category: "Tiffin" },
  { code: "110", name: "Uttapam", price: 85, category: "Tiffin" },
  { code: "201", name: "Chapati (2 pcs)", price: 60, category: "Breads" },
  { code: "202", name: "Parotta (2 pcs)", price: 70, category: "Breads" },
  { code: "203", name: "Butter Naan", price: 55, category: "Breads" },
  { code: "204", name: "Garlic Naan", price: 70, category: "Breads" },
  { code: "205", name: "Tandoori Roti", price: 40, category: "Breads" },
  { code: "301", name: "Paneer Butter Masala", price: 190, category: "Curries" },
  { code: "302", name: "Kadai Paneer", price: 200, category: "Curries" },
  { code: "303", name: "Dal Tadka", price: 140, category: "Curries" },
  { code: "304", name: "Dal Makhani", price: 170, category: "Curries" },
  { code: "305", name: "Chana Masala", price: 150, category: "Curries" },
  { code: "306", name: "Mixed Veg Curry", price: 160, category: "Curries" },
  { code: "307", name: "Chicken Curry", price: 210, category: "Curries" },
  { code: "308", name: "Butter Chicken", price: 260, category: "Curries" },
  { code: "309", name: "Mutton Rogan Josh", price: 320, category: "Curries" },
  { code: "401", name: "Veg Meals", price: 180, category: "Meals" },
  { code: "402", name: "Mini Meals", price: 120, category: "Meals" },
  { code: "403", name: "Non-Veg Meals", price: 240, category: "Meals" },
  { code: "404", name: "Sambar Rice", price: 90, category: "Rice" },
  { code: "405", name: "Curd Rice", price: 80, category: "Rice" },
  { code: "406", name: "Lemon Rice", price: 85, category: "Rice" },
  { code: "407", name: "Tomato Rice", price: 90, category: "Rice" },
  { code: "408", name: "Jeera Rice", price: 110, category: "Rice" },
  { code: "501", name: "Veg Fried Rice", price: 140, category: "Rice" },
  { code: "502", name: "Chicken Fried Rice", price: 180, category: "Rice" },
  { code: "503", name: "Veg Biryani", price: 170, category: "Biryani" },
  { code: "504", name: "Chicken Biryani", price: 220, category: "Biryani" },
  { code: "505", name: "Mutton Biryani", price: 320, category: "Biryani" },
  { code: "506", name: "Egg Biryani", price: 180, category: "Biryani" },
  { code: "601", name: "Filter Coffee", price: 40, category: "Beverages" },
  { code: "602", name: "Masala Tea", price: 30, category: "Beverages" },
  { code: "603", name: "Fresh Lime Soda", price: 60, category: "Beverages" },
  { code: "604", name: "Sweet Lassi", price: 70, category: "Beverages" },
  { code: "605", name: "Mango Lassi", price: 90, category: "Beverages" },
  { code: "606", name: "Buttermilk", price: 30, category: "Beverages" },
  { code: "607", name: "Cold Coffee", price: 110, category: "Beverages" },
  { code: "701", name: "Gulab Jamun (2 pcs)", price: 60, category: "Desserts" },
  { code: "702", name: "Rasmalai", price: 90, category: "Desserts" },
  { code: "703", name: "Vanilla Ice Cream", price: 70, category: "Desserts" },
  { code: "704", name: "Kulfi", price: 80, category: "Desserts" },
  { code: "705", name: "Payasam", price: 75, category: "Desserts" },
];

export const CATEGORIES = [
  "Tiffin",
  "Breads",
  "Curries",
  "Meals",
  "Rice",
  "Biryani",
  "Beverages",
  "Desserts",
];
